version: "3"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    command: server --console-address ":9001" /data
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  awslocal:
    image: amazon/aws-cli
    container_name: awslocal
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - "-c"
      - |
        while !  curl -o /dev/null -s -w "%{http_code}\n" http://minio:9000/minio/health/live | grep -q '200'; do
        echo 'Waiting for MinIO to be ready...';
        sleep 5;
        done &&
        echo 'MinIO is healthy.' &&
        echo 'Listing S3 buckets...' &&
        if aws --endpoint-url=http://minio:9000 s3 ls | grep -q 'il-panda-bucket'; then
        echo 'Bucket \"il-panda-bucket\" already exists.';
        else
        echo 'Bucket \"il-panda-bucket\" does not exist. Creating it...';
        aws --endpoint-url=http://minio:9000 s3 mb s3://il-panda-bucket &&
        echo 'Bucket \"il-panda-bucket\" created successfully.';
        fi
        if aws --endpoint-url=http://minio:9000 s3 ls | grep -q 'il-panda-private-bucket'; then
        echo 'Bucket \"il-panda-private-bucket\" already exists.';
        else
        echo 'Bucket \"il-panda-private-bucket\" does not exist. Creating it...';
        aws --endpoint-url=http://minio:9000 s3 mb s3://il-panda-private-bucket &&
        echo 'Bucket \"il-panda-private-bucket\" created successfully.';
        fi
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - minio

volumes:
  data:
