server:
  port: 8081
  servlet:
    context-path: /pancord

datasource:
  url: your-db-url
  username: your-db-username
  password: your-db--password
  driver-class-name: your-db-driver-class-name

# Minio configuration
minio:
  access:
    key: your-key
    secret: your-secret
  bucket.name: your-bucket
  private.bucket.name: your-private-bucket
  endpoint: your-minio-api-url
