server:
  port: 8081
  servlet:
    context-path: /pancord

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

cross:
  origins: http://localhost:3000

# Minio configuration
minio:
  access:
    key: ${minio.access.key}
    secret: ${minio.access.secret}
  bucket.name: ${minio.bucket.name}
  private.bucket.name: ${minio.private.bucket.name}
  endpoint: ${minio.endpoint}
